
name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Petal length of the 3rd versicolor observation
      id: petal-length-of-the-3rd-versicolor-observation
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Petal length of the 3rd versicolor observation
        setup-command: ''
        command: bash script.sh
        input: ''
        expected-output: '4.9'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PETAL-LENGTH-OF-THE-3RD-VERSICOLOR-OBSERVATION_RESULTS: "${{steps.petal-length-of-the-3rd-versicolor-observation.outputs.result}}"
      with:
        runners: petal-length-of-the-3rd-versicolor-observation
